baseURL = 'https://luis.land/blog/'
languageCode = 'es'
title = 'dev blog — luis.land'
theme = 'luisland'
publishDir = '../docs/blog'

[params]
  author = 'Luis Moyano'
  description = 'Notes about things I build; JSON Logic, Everything Ruby, and more.'
  homeURL = 'https://luis.land'

[markup.goldmark.renderer]
  unsafe = true
